
services:
  auth-service:
    build: ./commenta-auth-service
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - YOUTUBE_CLIENT_ID=${YOUTUBE_CLIENT_ID}
      - YOUTUBE_CLIENT_SECRET=${YOUTUBE_CLIENT_SECRET}
      - YOUTUBE_REDIRECT_URI=${YOUTUBE_REDIRECT_URI}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - DB_OPS_URL=http://db-ops-service:5000
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - db-ops-service
    restart: unless-stopped
  
  comment-fetcher-service:
    build: ./commenta-comment-fetching
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - FRONTEND_URL=${FRONTEND_URL}
      - DB_OPS_URL=http://db-ops-service:5000
      - AUTH_SERVICE_URL=http://auth-service:4000
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - db-ops-service
      - auth-service
    restart: unless-stopped
  
  ai-analytics-service:
    build: ./commenta-ai-analytics
    ports:
      - "4002:4002"
    environment:
      - PORT=4002
      - FRONTEND_URL=${FRONTEND_URL}
      - DB_OPS_URL=http://db-ops-service:5000
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - db-ops-service
    restart: unless-stopped
  
  db-ops-service:
    build: ./commenta-db-ops
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
    restart: unless-stopped
  
  ai-agent-service:
    build: ./commenta-ai-agent
    ports:
      - "4003:4003"
    environment:
      - PORT=4003
      - FRONTEND_URL=${FRONTEND_URL}
      - DB_OPS_URL=http://db-ops-service:5000
      - AUTH_SERVICE_URL=http://auth-service:4000
      - MCP_GATEWAY_URL=http://mcp-gateway:5001
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
    depends_on:
      - db-ops-service
      - mcp-gateway
    restart: unless-stopped

  mcp-gateway:
    build: ./commenta-mcp
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DB_OPS_URL=http://db-ops-service:5000
    depends_on:
      - db-ops-service
    restart: unless-stopped